export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_SETUP_STEP = 'UPDATE_SETUP_STEP';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const CHNAGE_USERNAME = 'CHNAGE_USERNAME'
export const SET_COMMUNITY_DOMAIN = 'SET_COMMUNITY_DOMAIN'

